export const FETCH = 'FETCH';
export const RECEIVE_DEVICES = 'RECEIVE_DEVICES';
export const UPDATE_DEVICE = 'UPDATE_DEVICE';
export const RECEIVE_USER_CONFIG = 'RECEIVE_USER_CONFIG';
export const RECEIVE_JWT = 'RECEIVE_JWT';
export const RECEIVE_BOX_ID = 'RECEIVE_BOX_ID';
export const HTTP_ERROR = 'HTTP_ERROR';
